name: RioTrip
description: This app is for those who are traveling to Rio de Janeiro.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  http: ^0.13.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/map.png
    - assets/images/loading.png
    - assets/images/appbartitle.png
    - assets/images/area1.png
    - assets/images/area2.png
    - assets/images/area3.png
    - assets/images/area4.png
    - assets/images/area5.png
    - assets/images/area6.png
    - assets/images/area7.png
    - assets/images/area8.png
    - assets/images/area9.png
    - assets/images/area10.png
    - assets/images/area11.png
    - assets/images/area12.png
    - assets/images/area13.png
    - assets/images/area14.png
    - assets/images/area15.png
    - assets/images/area16.png
    - assets/images/area17.png
    - assets/images/area18.png
