name: RioTrip
description: This app is for those who are traveling to Rio de Janeiro.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  collection: ^1.17.0
  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  go_router: ^14.0.0
  path_to_regexp: ^0.4.0
  adaptive_navigation: ^0.0.3
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  http: ^0.13.3
  intl: ^0.17.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/category/
    - assets/weather/
